# Generated by Django 5.2.1 on 2025-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('message', models.TextField()),
                ('remind_via', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
            ],
        ),
    ]
