# Generated by Django 5.2.1 on 2025-05-10 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='remind_via',
        ),
        migrations.AddField(
            model_name='reminder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reminder',
            name='remind_by',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
